Repository TypeScriptAlpha/ProjetoTS, pull requests merged in 2024-06, with the labels that each got.

#5 feat: Created all delete routes
  src/entities/User.ts
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/useCases/DeleteTeam/DeleteTeamController.ts
  src/useCases/DeleteTeam/DeleteTeamDTO.d.ts
  src/useCases/DeleteTeam/DeleteTeamUseCase.ts
  src/useCases/DeleteTeam/index.ts
  src/useCases/DeleteUser/DeleteUserController.ts
  src/useCases/DeleteUser/DeleteUserDTO.d.ts
  src/useCases/DeleteUser/DeleteUserUseCase.ts
  src/useCases/DeleteUser/index.ts
  src/useCases/DeleteUserFromTeam/DeleteUserFromTeamController.ts
  src/useCases/DeleteUserFromTeam/DeleteUserFromTeamDTO.d.ts
  src/useCases/DeleteUserFromTeam/DeleteUserFromTeamUseCase.ts
  src/useCases/DeleteUserFromTeam/index.ts
  src/useCases/LoginUser/loginUserUseCase.ts
  src/useCases/LogoutUser/LogoutUserController.ts
  src/useCases/LogoutUser/index.ts
Labels: feat

#6 feat: GetOwnUser routes created
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/types/types.d.ts
  src/useCases/CreateUser/CreateUserController.ts
  src/useCases/GetOwnUser/GetOwnUserController.ts
  src/useCases/GetOwnUser/GetOwnUserUseCase.ts
  src/useCases/GetOwnUser/index.ts
  src/useCases/ListAllUsers/ListAllUsersController.ts
  src/useCases/LoginUser/loginUserController.ts
  tsconfig.json
Labels: feat, fix, help wanted

#7 feat: Created patch routes
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/types/types.d.ts
  src/useCases/GetOwnUser/GetOwnUserController.ts
  src/useCases/LoginUser/loginUserUseCase.ts
  src/useCases/UpdateTeam/UpdateTeamController.ts
  src/useCases/UpdateTeam/UpdateTeamDTO.d.ts
  src/useCases/UpdateTeam/UpdateTeamUseCase.ts
  src/useCases/UpdateTeam/index.ts
  src/useCases/UpdateUser/UpdateUserController.ts
  src/useCases/UpdateUser/UpdateUserDTO.d.ts
  src/useCases/UpdateUser/UpdateUserUseCase.ts
  src/useCases/UpdateUser/index.ts
Labels: feat

#9 feat: GetTeamById routes created
  src/entities/User.ts
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/types/types.d.ts
  src/useCases/GetTeamById/GetTeamController.ts
  src/useCases/GetTeamById/GetTeamUseCase.ts
  src/useCases/GetTeamById/index.ts
  src/useCases/LoginUser/loginUserController.ts
Labels: feat

#10 feat: GetTeamMembers routes created
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/useCases/GetTeamMembers/GetTeamMembersController.ts
  src/useCases/GetTeamMembers/GetTeamMembersUseCase.ts
  src/useCases/GetTeamMembers/index.ts
Labels: feat

#12 feat: Implemented admin update user privileges
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/useCases/UpdateUser/UpdateUserController.ts
  src/useCases/UpdateUser/UpdateUserUseCase.ts
  src/useCases/getUser/getUserController.ts
Labels: feat

#11 feat: add POST routes for /teams and /teams/:team_id/member/:user_id
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/useCases/CreateTeam/CreateTeamController.ts
  src/useCases/CreateTeam/CreateTeamDTO.d.ts
  src/useCases/CreateTeam/CreateTeamUseCase.ts
  src/useCases/CreateTeam/index.ts
  src/useCases/setMember/index.ts
  src/useCases/setMember/setMemberController.ts
  src/useCases/setMember/setMemberDTO.d.ts
  src/useCases/setMember/setMemberUseCase.ts
Labels: feat

#14 feat: add route get /teams
  src/repository/UserRepository.ts
  src/repository/implemetations/PostgressUserRepository.ts
  src/routes/routes.ts
  src/useCases/ListAllTeams/ListAllTeamsController.ts
  src/useCases/ListAllTeams/ListAllTeamsUseCase.ts
  src/useCases/ListAllTeams/index.ts
Labels: feat

#16 fix: Fixed some logic errors, adjusted jwt and removed some console.log
  src/repository/implemetations/PostgressUserRepository.ts
  src/useCases/ListAllTeams/ListAllTeamsController.ts
  src/useCases/LoginUser/loginUserUseCase.ts
  src/useCases/UpdateUser/UpdateUserUseCase.ts
  src/useCases/setMember/setMemberUseCase.ts
Labels: bug, fix

#17 feat: Created custom request interface to avoid change files on node_modules.
  src/middleware/authenticate.ts
  src/useCases/CreateTeam/CreateTeamController.ts
  src/useCases/DeleteTeam/DeleteTeamController.ts
  src/useCases/DeleteUser/DeleteUserController.ts
  src/useCases/DeleteUserFromTeam/DeleteUserFromTeamController.ts
  src/useCases/GetOwnUser/GetOwnUserController.ts
  src/useCases/GetTeamById/GetTeamController.ts
  src/useCases/ListAllTeams/ListAllTeamsController.ts
  src/useCases/ListAllUsers/ListAllUsersController.ts
  src/useCases/UpdateTeam/UpdateTeamController.ts
  src/useCases/UpdateUser/UpdateUserController.ts
  src/useCases/getUser/getUserController.ts
  src/useCases/setMember/setMemberController.ts
Labels: feat
